# action.yml
name: 'Publish Dart/Flutter package'
description: 'Publish Dart/Flutter package'
inputs:
  credential:
    description: 'Google Account credential'
    required: true
  flutter_package:
    description: '(Optional) Publish packages type. (default: true)'
    required: false
    default: true
  skip_test:
    description: '(Optional) Skip test (default: false)'
    required: false
    default: false
  package_directory:
    description: '(Optional) Package directory (default: ".")'
    required: false
    default: '.'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
