on:
  push:
    branches:
      - 'test/*'
      - '!master'
jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Test action
        uses: ./
        with:
          credential: "{}"
          package_directory: "."
          skip_test: true
